#! /bin/sh

xrandr --output DP-3 --primary --left-of DP-0

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-3 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

nitrogen --set-scaled ~/Documents/rust.jpg --head=0
nitrogen --set-scaled ~/Documents/rust.jpg --head=1

pkill -x polybar > /dev/null 
polybar DP-0 &
polybar DP-3 &

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         38

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox:Navigator desktop='^2'
bspc rule -a Code:code desktop='^6'
bspc rule -a Element:element desktop='^7'
bspc rule -a Slack:slack desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a Zulip:zulip desktop='^10'

