#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V

nitrogen --set-scaled ~/Documents/rust.png --head=0

pkill -x polybar > /dev/null
polybar eDP-1 &

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         38

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox:Navigator desktop='^2'
bspc rule -a Code:code desktop='^6'
bspc rule -a Element:element desktop='^7'
bspc rule -a Slack:slack desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a Zulip:zulip desktop='^10'
